import re

MIXED_CASE_ABBREVIATIONS = [
    # Abbreviations
    ('Comm.', 'Committee'),
    ('Educ.', 'Education'),
    ('Fed.', 'Federal'),
    ('Fin.', 'Finance'),
    ("Gov't.", 'Government'),
    ("Gov't", 'Government'),
    ('Prem.', 'Premier'),
    ('Prov.', 'Provincial'),
    ('Res.', 'Resolution'),
    ('Yar.', 'Yarmouth'),

    # Acronyms
    ('C.B.', 'Cape Breton'),
    ('L.N.G.', 'Liquified Natural Gas'),
    ('N.S.', 'Nova Scotia'),
]

UPPER_CASE_ABBREVIATIONS = [
    # Ambigious abbreviations
    ('ADDICTION SERV.', 'Addiction Services'),
    ('ASSAULT SERV.', 'Assault Services'),
    ('CARE SERV.', 'Care Services'),
    ('COM. SERV.', 'Community Services'),
    ('COMMUN. SERV.', 'Community Services'),
    ('EMERGENCY SERV.', 'Emergency Services'),
    ('OXYGEN SERV.', 'Oxygen Services'),
    ('PSYCHOLOGY SERV.', 'Psychology Services'),
    ('ACAD. FED.', 'Acadian Federation'),
    ('TURKEY FED.', 'Turkey Federation'),
    ('TIM HORTONS HOSP.', 'Tim Hortons Hospitality'),
    ('GAS REG.', 'Gas Regulation'),
    ('REG. Nurse', 'Registered Nurse'),

    # Abbreviations
    ('ADMIN.', 'Administration'),
    ('ADV.', 'Advanced'),
    ('AFFS.', 'Affairs'),
    ('AGRIC.', 'Agriculture'),
    ('AMT.', 'Amount'),
    ('ANNA.', 'Annapolis'),
    ('ANNIV.', 'Anniversary'),
    ('APPT.', 'Appointment'),
    ('ASSOC.', 'Association'),
    ('ATL.', 'Atlantic'),
    ('AUTH.', 'Authority'),
    ('BD.', 'Board'),
    ('BDS.', 'Boards'),
    ('BDS', 'Boards'),
    ('BLDG.', 'Building'),
    ('BLDGS.', 'Buildings'),
    ('BUS.', 'Business'),
    ('CAN.', 'Canada'),
    ('CAP.', 'Capital'),
    ('CDN.', 'Canadian'),
    ('CENT.', 'Central'),
    ('CFLs', 'Compact Fluorescent Lamps'),
    ('CONS.', 'Consolidated'),
    ('CORP.', 'Corporation'),
    ('CTR.', 'Centre'),
    ('CTR', 'Centre'),
    ('CTRS.', 'Centres'),
    ('CO.', 'County'),
    ('COL.', 'Colchester'),
    ('COS.', 'Counties'),
    ('COM.', 'Community'),
    ('COMM.', 'Committee'),
    ('COMMN.', 'Commission'),
    ('COMMUN.', 'Community'),
    ('COMP.', 'Competition'),
    ('CONGRATS.', 'Congratulations'),
    ('CONST.', 'Construction'),
    ('COUN.', 'Council'),
    ('CUMB.', 'Cumberland'),
    ('DART.', 'Dartmouth'),
    ('DEP.', 'Deputy'),
    ('DEPT.', 'Department'),
    ('DEV.', 'Development'),
    ('DIST.', 'District'),
    ('EAST.', 'Eastern'),
    ('ECON.', 'Economic'),
    ('ED.', 'Education'),
    ('EDUC.', 'Education'),
    ('ELEM.', 'Elementary'),
    ('EMERG.', 'Emergency'),
    ('ENVIRON.', 'Environment'),
    ('EQUIP.', 'Equipment'),
    ('EXEC.', 'Executive'),
    ('EXECS.', 'Executives'),
    ('FAM.', 'Family'),
    ('FDN.', 'Foundation'),
    ('FED.', 'Federal'),
    ('FIN.', 'Finance'),
    ('FISH.', 'Fisheries'),
    ('FL.', 'Floor'),
    ('GEN.', 'General'),
    ("GOV.'T.", 'Government'),
    ("GOV'T.", 'Government'),
    ("GOV'T", 'Government'),
    ('GRAD.', 'Graduate'),
    ('GRAD', 'Graduate'),
    ('GRADS.', 'Graduates'),
    ('GRADS', 'Graduates'),
    ('HBR.', 'Harbour'),
    ('HFX.', 'Halifax'),
    ('HOSP.', 'Hospital'),
    ('HR.', 'Hour'),
    ('HWY.', 'Highway'),
    ('IND.', 'Industry'),
    ('INFO.', 'Information'),
    ('INFO', 'Information'),
    ('INIT.', 'Initiative'),
    ('INSTIT.', 'Institute'),
    ('INTL.', 'International'),
    ('LBR.', 'Labour'),
    ('LEG.', 'Legislative'),
    ('LOC.', 'Local'),
    ('LTD.', 'Limited'),
    ('LUN.', 'Lunenburg'),
    ('LWR.', 'Lower'),
    ('MAR.', 'Maritime'),
    ('MED.', 'Medical'),
    ('MGT.', 'Management'),
    ('MIN.', 'Minister'),
    ('MUN.', 'Municipal'),
    ('NAT.', 'Natural'),
    ("NAT'L.", 'National'),
    ('NATL.', 'National'),
    ('PAYT.', 'Payment'),
    ('PERF.', 'Performance'),
    ('PKG.', 'Package'),
    ('PMT.', 'Payment'),
    ('PR', 'Public Relations'),
    ('PREM.', 'Premier'),
    ('PREM', 'Premier'),
    ('PROG.', 'Program'),
    ('PROGS.', 'Programs'),
    ('PROJ.', 'Project'),
    ('PROV.', 'Provincial'),
    ('PUB.', 'Public'),
    ('RD.', 'Road'),
    ('RDS.', 'Roads'),
    ('REF.', 'Reference'),
    ('REG.', 'Regional'),
    ('REGS.', 'Regulations'),
    ('REPT.', 'Report'),
    ('REPTS.', 'Reports'),
    ('RES.', 'Resources'),
    ('RTE.', 'Route'),
    ('RYL.', 'Royal'),
    ('SEPT.', 'September'),
    ('SO.', 'South'),
    ('SCH.', 'School'),
    ('SOC.', 'Society'),
    ('SERV.', 'Service'),
    ('SM.', 'Small'),
    ('SRV.', 'Services'),
    ('STA.', 'Station'),
    ('STATS.', 'Statistics'),
    ('TECH.', 'Technician'),
    ('TECHS.', 'Technicians'),
    ('TEL.', 'Telephone'),
    ('W.', 'West'),
    ('YAR.', 'Yarmouth'),
    ('YR.', 'Year'),
    ('YRS.', 'Years'),

    # Acronyms
    ('B.C.', 'British Columbia'),
    ('C.B.', 'Cape Breton'),
    ('CBRM', 'Cape Breton Regional Municipality'),
    ('CCH', 'Communities, Culture and Heritage'),
    ('CF', 'Cystic Fibrosis'),
    ('CFS', 'Canadian Forces Station'),
    ('CNSOPB', 'Canada-Nova Scotia Offshore Petroleum Board'),
    ('DHA', 'District Health Authorities'),
    ('DHAs', 'District Health Authorities'),
    ('DIS', 'Drug Information System'),
    ('DSTN', 'DSME Trenton Ltd'),
    ('EECD', 'Education and Early Childhood Development'),
    ('EI', 'Employment Insurance'),
    ('EIBI', 'Early Intensive Behavioural Intervention'),
    ('EMO', 'Emergency Management Office'),
    ('ERDT', 'Economic and Rural Development and Tourism'),
    ('HRM', 'Halifax Regional Municipality'),
    ('LAE', 'Labour and Advanced Education'),
    ('LFA', 'Lobster Fishing Area'),
    ('LWD', 'Labour and Workforce Development'),
    ('MOU', 'Memorandum of Understanding'),
    ('N.B.', 'New Brunswick'),
    ('N.S.', 'Nova Scotia'),
    ('NSGEU', 'Nova Scotia Government and General Employees Union'),
    ('NSLC', 'Nova Scotia Liquor Corporation'),
    ('NSP', 'Nova Scotia Power'),
    ('OAS', 'Old Age Security'),
    ('P.E.I.', 'Prince Edward Island'),
    ('PSC', 'Public Service Commission'),
    ('QP', 'Question Period'),
    ('RRFB', 'Resource Recovery Fund Board'),
    ('SNS', 'Service Nova Scotia'),
    ('SNSMR', 'Service Nova Scotia and Municipal Relations'),
    ('SWSDA', 'South West Shore Development Authority'),
    ('TIR', 'Transportation and Infrastructure Renewal'),
    ('URB', 'Utility and Review Board'),
    ('WCB', "Workers' Compensation Board"),

    # Must come after "P.E.I.".
    ('E.', 'East'),
    # Must come after "N.S.".
    ('S.', 'South'),
]

upper_case_words = (
    'CBC',
    'CCSVI',  # too long
    'DSME',  # trade name
    'II',
    'MLA',
    'NDP',
    'NDP:',
    'NSCAD',  # trade name
    'RCMP',
)

mixed_case_abbreviations = []
for old, new in MIXED_CASE_ABBREVIATIONS:
    pattern = r'\b' + re.escape(old)
    if not old.endswith('.'):
        pattern += r'\b'
    mixed_case_abbreviations.append((re.compile(pattern), new))

upper_case_abbreviations = []
for old, new in UPPER_CASE_ABBREVIATIONS:
    pattern = r'\b' + re.escape(old)
    if not old.endswith('.'):
        pattern += r'\b'
    upper_case_abbreviations.append((re.compile(pattern), new))
